### ISSUE TITLE
EN_US

### ISSUE THREAD

**Issue by dbnschools** [wiris/moodle-filter_wiris#12] opened 2017-07-20 10:57 UTC
We are having an issue when using English US as the default language for Moodle.  It breaks the buttons in the atto editor.  We get a 404 error in the browser for the language string.  Editor/atto/plugins/wiris/lang/en_us is missing.  I copied the en folder and made it en_us and the editor started working again.

**Comment by manuelwiris** [comment] 2017-08-08 13:56
Hi @dbnschools  

Thanks for your feedback. 

The issue is fixed with our las release #14 

Best, regards

**Closed by manuelwiris** 2017-08-08 13:56 UTC
