### ISSUE TITLE
Latest release does not work in IE11

### ISSUE THREAD

**Issue by Syxton** [wiris/moodle-filter_wiris#5] opened 2017-03-02 15:42 UTC
Testing in IE 11.576.14393.0
Tested both Atto and Tinymce using the latest plugins of Wiris 4.1.0.1357
Running Moodle 3.1.3+

Can't move equation from Wiris popup to Moodle editor.
When viewing previously saved equations, the filter is not processing inside the editor.

**Comment by manuelwiris** [comment] 2017-03-03 08:06
Hi Syxton, 

Seems there is a problem with Internet Explorer and SVG  embedded fonts, if the SVG is URL encoded.

We will try to fix this issue as soon as posible. Meanwhile, you can edit` filter/wiris/configuration.ini `file and set the variable wirispluginperformance = false.

Sorry for the inconvenience,

**Comment by Syxton** [comment] 2017-03-03 13:23
@manuelwiris Thank you for the quick response.  After uncommenting the wirispluginperformance = false line of the configuration.ini file the equations are filtered in the editor correctly.  

However, it is now unable to open the wiris editor without crashing the entire browser.

**Comment by manuelwiris** [comment] 2017-03-06 07:35
Syxton, 

Could you provide us more information about your error? There is some javascript error on your browser console?

**Comment by Syxton** [comment] 2017-03-06 13:24
@manuelwiris 
When #wirispluginperformance = false is commented out.  
Using Atto: I get an "Invalid Character" error in the console: line 1948 of atto/plugins/wiris/core/core.js
That is this line:  result = JSON.parse(wrs_getContent(_wrs_conf_showimagePath, data));

When using TinyMCE: I get "Unable to get property 'call' of undefined or null reference" from tiny_mce.js and "Invalid character" in the tinmcy wiris plugin core.js on the line 1984 (Same line)

When  wirispluginperformance = false is NOT commented out.  

Atto: It works.
TinyMCE: The filter seems to work, but the popup editor crashes the browser before an error can be output.

**Comment by manuelwiris** [comment] 2017-03-07 16:03
@Syxton 

The new release (4.1.1) fix's the problem with I.E and the performance mode.

However we are still working with the conflict between Internet Explorer and TinyMCE. The bug will be fixed in our April release. 

Best,

**Comment by manuelwiris** [comment] 2017-04-06 12:50
@Syxton 

The issue is fixed in our last release (4.2.0)

Thanks for your feedback,

**Closed by manuelwiris** 2017-04-06 12:50 UTC
