### ISSUE TITLE
FR: Move configuration.ini to moodledata or into the database

### ISSUE THREAD

**Issue by danowar2k** [wiris/moodle-filter_wiris#79] opened 2021-06-03 08:43 UTC
The current style to change some of the configuration of this plugin is to store it in the file https://github.com/wiris/moodle-filter_wiris/blob/stable/configuration.ini.dist (without the .dist suffix).

This is kind of the only Moodle plugin I know of that stores configuration data in the code folder. Could you please move that part of the configuration to either entries in the Moodle config_plugins table or to a Wiris folder inside moodledata?

Leaving the configuration in the code folder may lead to problems and additional steps during deployment of new plugin versions or to possibly ignoring the configuration because of the unusual storing point.

EDIT: The storing point is maybe something used for each and every Wiris plugin. If that is the case, changing the path for Wiris for Moodle only would of course not be feasible. But you could abstract away from the concrete configuration file, its path and how to read it, and then you could have a "general way" (as a file, in the plugin folder) and a Moodle plugin way (in the db or in moodledata as a file)

**Comment by dcanet-at-wiris** [comment] 2021-12-30 13:37
Hi, @danowar2k 

First of all, I apologize for my late answer. 🙏🏿 

Not that we didn't knew about your suggestion, since it's such a valid point. It's more that we didn't find the moment to answer your request accordingly. 

So, let's fix that. 😃 

Below, I will dig a bit on the details of the issue and the motivations behind this decision.

Regarding this particular case, **I will be proposing a "Feature request issue" so we can work on a consistent solution** that will avoid the limitations of the current implementation.

Finally, and If you allow me, I will be closing this issue and I will add a reference to the new Feature request issue, once documented.

### Context

>_"This is kind of the only Moodle plugin I know of that stores configuration data in the code folder. Could you please move that part of the configuration to either entries in the Moodle config_plugins table or to a Wiris folder inside moodledata?"
> "Leaving the configuration in the code folder may lead to problems and additional steps during deployment of new plugin versions or to possibly ignoring the configuration because of the unusual storing point."_

You are totally right. Using the code folder to store plugin's configuration settings is not good practice at all, in terms of Moodle.

And, as you mention, it can lead to problems to future developers. 

### Issue definition

Therefore, imho we'd need to define the issue in terms of the what is the main problem to solve:

"This plugin stores (some of) its configuration's settings data in the plugin's root folder, using a static file named  [configuration.ini.dist](../configuration.ini.dist), instead of a more Moodle's native way like [`config_plugins` tables](https://docs.moodle.org/dev/Admin_settings) or the [Moodledata directory](https://docs.moodle.org/22/en/Moodledata_directory)."

### Motivation behind this decision

The [/configuration.ini.dist](../configuration.ini.dist) is part of the "MathType Web Integration PHP" library filter that allows Moodle to access the render services provided by the Wiris API.

The "MathType Web Integration" library is available for PHP, Java, Rails and .Net back-end languages.

> For more details, visit [MathType Configuration table docs page][doc-config] 

The reasons to keep this file on the Moodle's root folder are:

- Compatibility with other PHP platforms where the MathType Web Integrations PHP library is used.
- Software maintanability: [the same strategy is used for other back-end platforms like .Net, Java or Rails][doc-config].
- Historical reasons: this library is being used for more than a decade now, so any solution we may come with should aim for complete backward compatibility.  
- Therefore, It would require a new feature request to specify which problem needs to be solved and a proposed solution.

So let's define then how this solution would look like, so we can complete the feature request issue. 

### Expected behavior

The plugin will expose "MathType Web Integration PHP" library configuration settings using Moodle's Admin settings UI, instead of the [configuration.ini.dist](../configuration.ini.dist) configuration file.

Admin users will be able to manage the MathType Web Integration Library Server configuration file (configuration.ini) settings using Moodle's UI.

The configuration settings data will be stored using Moodle plugins development best practices. Like [`config_plugins` tables](https://docs.moodle.org/dev/Admin_settings), the [Moodledata directory](https://docs.moodle.org/22/en/Moodledata_directory).

At the same time, we want to offer backward compatibility with Moodle installations using the current [configuration.ini.dist](../configuration.ini.dist) method.

Therefore, the solution proposed must also include an upgrade path when updating to this version of the plugin. 

So it would need to be decided what to do if the  [/configuration.ini.dist](/configuration.ini.dist) file already exists on a Moodle's instance. 



[doc-config]:https://docs.wiris.com/en/mathtype/mathtype_web/integrations/config-table#server_configuration_file_configurationini

**Closed by dcanet-at-wiris** 2021-12-30 13:37 UTC
Labels: type:enhancement, state:accepted

**Comment by dcanet-at-wiris** [comment] 2021-12-30 14:01
Update: See #91 "Manage MathType Web Integration configuration data dinamically using Moodle's Admin settings UI".
